export const getPropertyTypes = () => [
  "Hotel",
  "Hostels",
  "Apartments",
  "Villas",
  "House",
  "Guest House",
  "Bed & Breakfast (B&B)",
  "Resorts",
  "Motel",
  "Boutique Hotel",
  "Farm Stay",
  "Cabin",
  "Chalet",
  "Cottage",
  "Camping",
  "Tree House",
  "Boat",
];
